'use strict';
import gulp from 'gulp'
import {argv} from 'yargs'
import Help from 'gulp-task-help'
import {clean, buildBabel} from 'mitmaro-gulp-tasks';

const options = {
    destination: argv.destination || './stubs',
    clean: argv.clean || true
};

const data = {
    cleanPatterns: [options.destination],
    sources: ['./src/**/**.js']
};

const help = new Help(
    'Gulp Task: Help'
);

help.registerArgument(
    'clean', 'Run clean before running tasks.', 'true'
);

help.registerArgument(
    'destination', 'The build files destination directory.', 'stubs'
);

help.registerTask(
    'clean',
    'Removed all files and folders generated by the build'
);

help.registerTask(
    'help',
    'Shows information on the usage of gulp.'
);
help.registerTask(
    'build',
    'Builds the project',
    ['clean'],
    ['destination', 'clean']
);

gulp.task('clean', clean(data.cleanPatterns, options));
gulp.task('build', ['clean'], buildBabel(data.sources, options.destination));
gulp.task('help', help.helpTask);
gulp.task('default', ['help']);
